### ISSUE TITLE
The Long And Winding Road to v-next

### ISSUE THREAD

**Issue by yamamoto-febc** [sacloud/terraform-provider-sakuracloud#576]
v2.0リリースまでのタスクトラッキング用Issue

### v2.0について

- [Design](https://github.com/sacloud/terraform-provider-sakuracloud/blob/master/design/v2.md)

### 開発関連タスク

- [x] Libsacloud v2の利用
- [x] Acceptance Testの改善
  - [x] Libsacloud v2のfakeドライバーを利用し、オフラインでAccTest可能にする(#564)
  - [x] テスト時に作成するリソースの命名規則統一(#578)
  - [x] リソースのクリーンアップ処理(#578)
  - [x] テストの安定性向上(#566, #569, #570, #571, #572, #574, #575, #577, #578)
- [x] terraform-providersでのコーディングスタイル/規約の踏襲(#579, #581, #585)
- [x] タイムアウト関連パラメータの整理(#583, #584)
- [x] ゾーンの扱いを整理(#587)
- [x] 2019/12 新機能対応(#607)
- ~[ ] ログ出力箇所の検討/実装~

### リリース/ドキュメント関連

- [x] リリースプロセスの修正(#655)
- [x] マニュアルの複数バージョン対応
  - [x] 日本語版ドキュメントの切り出し(#615)
  - [x] v2向けマニュアルの整備(#629, #630, #641, https://github.com/sacloud/docs.usacloud.jp/pull/7)
  - [x] アップグレードガイドの整備(https://github.com/sacloud/docs.usacloud.jp/pull/9)
- [x] Terraform Registryでのプロバイダー配布対応

### タスク: スキーマ変更関連

- [x] DataSourceでのFilter周りの整理
- [x] サーバリソースでのNIC周りの整理
- [x] サーバリソースでのディスク修正パラメータ周りの整理(#589)
- [x] 親子リソースの整理
- [x] Terraform Plugin Best Practicesの踏襲(#579)
- [x] その他スキーマパラメータの確認/見直し(不要な`Computed:true`など)(#588)

ref: https://www.terraform.io/docs/extend/best-practices/index.html

### その他

- [x] 実環境での運用テスト(usacloud.jp)

[`v2`ラベルの付いたIssue/PR](https://github.com/sacloud/terraform-provider-sakuracloud/labels/v2)
